# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('sensor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('humidity', models.IntegerField(default=0)),
                ('pressure', models.IntegerField(default=0)),
                ('temperature', models.IntegerField(default=0)),
                ('min_humidity', models.IntegerField(default=0)),
                ('max_humidity', models.IntegerField(default=0)),
                ('avg_humidity', models.IntegerField(default=0)),
                ('min_pressure', models.IntegerField(default=0)),
                ('max_pressure', models.IntegerField(default=0)),
                ('avg_pressure', models.IntegerField(default=0)),
                ('min_temp', models.IntegerField(default=0)),
                ('max_temp', models.IntegerField(default=0)),
                ('avg_temp', models.IntegerField(default=0)),
            ],
        ),
    ]
