# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0005_auto_20161119_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='color',
            field=models.CharField(default='D1F2A5', max_length=6),
            preserve_default=False,
        ),
    ]
